// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $docs_path_ from "./routes/docs/[path].tsx";
import * as $download from "./routes/download.tsx";
import * as $index from "./routes/index.tsx";
import * as $DownloadButton from "./islands/DownloadButton.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/docs/[path].tsx": $docs_path_,
    "./routes/download.tsx": $download,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/DownloadButton.tsx": $DownloadButton,
    "./islands/Navbar.tsx": $Navbar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
